### ISSUE TITLE
[BUG] Attack throws "Cannot read properties of undefined" with all actors

### ISSUE THREAD

**Issue by dimonic** [tonyrobots/dcc-qol#2] opened 2024-08-11 13:11 UTC
Foundry version 12.330
DCC-QoL version 0.0.23
Other Modules: none

Steps to reproduce: Foundry + DCC Core compendium, enable QoL, Set all settings to default values. Drag Ogre token (or any other) to scene, double click, go to equipment, click dice to attack. Error thrown, nothing in chat box.

**Comment by tonyrobots** [comment] 2024-08-16 01:03
Strange! Which version of the DCC system are you using? 

Will investigate tomorrow and report back. Thanks, @dimonic.

**Comment by tonyrobots** [comment] 2024-08-16 02:21
I'm not able to reproduce this issue; are you using DCC system version 0.45 or higher?

**Comment by tonyrobots** [comment] 2024-09-06 00:51
Closing issue without further feedback, can re-open if we can find a way to reproduce.

**Closed** 2024-09-06 00:51 UTC
